/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolab2proje3netbeans;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static prolab2proje3netbeans.Prolab2proje3netbeans.connectdb;
import static prolab2proje3netbeans.Prolab2proje3netbeans.database;

/**
 *
 * @author melih
 */
public class DataBase extends javax.swing.JFrame {

    /**
     * Creates new form DataBase
     */
    public static int connect_state=2;
    
    public DataBase() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Database Bağlama (Lütfen Notları Okuyunuz)");
        setMinimumSize(new java.awt.Dimension(650, 600));
        setPreferredSize(new java.awt.Dimension(650, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setText("Bağlayacağınız Server User İsmi");
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 190, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 110, -1));

        jTextField3.setEditable(false);
        jTextField3.setText("Bağlayacağınız Server Şifresi(Eğer Varsa)");
        jTextField3.setBorder(null);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 230, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 110, -1));

        jButton1.setText("Bağlan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jTextField5.setEditable(false);
        jTextField5.setText("Örnek: root");
        jTextField5.setBorder(null);
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 70, -1));

        jTextField6.setEditable(false);
        jTextField6.setText("\"jdbc:mysql://localhost:3306/netflixdatabase?serverTimezone=UTC\",\"root\",\"Abcd.1234\"");
        jTextField6.setBorder(null);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 440, -1));

        jTextField7.setEditable(false);
        jTextField7.setText("Örnek: Abcd.1234");
        jTextField7.setBorder(null);
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 100, -1));

        jTextField8.setEditable(false);
        jTextField8.setText("Örnek Olarak Bağlandığınızda Oluşacak Connection Stringi Aşşağıdadır.");
        jTextField8.setBorder(null);
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 350, -1));

        jTextField9.setEditable(false);
        jTextField9.setText(" Eğer Bir Bağlantı Problemi Yaşıyorsanız Problem DataBase'in Bağlanmasındadır.");
        jTextField9.setBorder(null);
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 264, -1, 20));

        jTextField10.setEditable(false);
        jTextField10.setText("Gönderdiğimiz .sql Uzantılı Database'i İmport Edeceğiniz Şemanın Adını \"netflixdatabase\" Yapınız.");
        jTextField10.setBorder(null);
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 550, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-warning-26.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Hocam bu paneli yapmamızın sebebi MySQL'in çalışması için bir server'a ihtiyacı olduğundandır.\nNormal şartlarda yaptığımız database'i SQLite ile size bu arayüzü yapmadan gönderebilirdik ama\nSQLite'da MySQL'deki gibi Stored Procedures kısmı olmadığı için MySQL ile böyle bir çözüm ürettik.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 550, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-warning-26.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jTextField11.setEditable(false);
        jTextField11.setText("Bağlayacağınız Server Host Name");
        jTextField11.setBorder(null);
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 200, -1));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 110, -1));

        jTextField13.setEditable(false);
        jTextField13.setText("Örneğin: localhost");
        jTextField13.setBorder(null);
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Prolab2proje3netbeans.server_name=jTextField2.getText();
        Prolab2proje3netbeans.server_password=jTextField4.getText();
        Prolab2proje3netbeans.host_name=jTextField12.getText();
        Connection myc =connectdb();
        if(myc==null){
            
            JOptionPane.showMessageDialog(database,"Bağlantı Kurulamadı. Lütfen Girdiğiniz Bilgilere Dikkat Ediniz");
            
        
        }else{
//DELIMITER //
//CREATE DEFINER=`root`@`localhost` PROCEDURE `update_rates7`(
//IN prg_id INT(4)
//)
//BEGIN 
//declare ort_rate INT ;
//SELECT AVG(kullanıcı_puanı) INTO ort_rate FROM kullanıcıprogramtablosu where kullanıcıprogramtablosu.program_id=prg_id;
//
//
//UPDATE programtablosu SET programtablosu.program_ortpuan=ort_rate where programtablosu.program_id=prg_id;
//END //
//DELIMITER ;
            
            
            
            
            
            database.setVisible(false);
            kullanicigiris KG =new kullanicigiris();
            KG.setVisible(true); 
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
