/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolab2proje3netbeans;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import static java.lang.Integer.parseInt;
import static java.lang.System.currentTimeMillis;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.ParseException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static prolab2proje3netbeans.Prolab2proje3netbeans.connectdb;
import static prolab2proje3netbeans.kullaniciarayüz.email;

/**
 *
 * @author melih
 */
public class filmarayüz extends javax.swing.JFrame {

    /**
     * Creates new form filmarayüz
     */
    public static int prg_id;
    public static long baslangic_süresi=0;
    public static long izleme_süresi;
    public static String k_email;
    public static long toplam_izlenmesüresi;
   
    
    public filmarayüz(int prg_id,String k_email) {
        initComponents();
        jButton4.setVisible(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    
        this.prg_id=prg_id;
        
        this.k_email=k_email;
        jButton2.setVisible(false);
        int bölüm_sayisi = 0;
        
        try {
			Connection myConn=connectdb();
			Statement myStat= (Statement) myConn.createStatement();
			ResultSet myRs=  ((java.sql.Statement) myStat).executeQuery("SELECT * FROM programtablosu WHERE program_id='"+prg_id+"'");
                        
                        while(myRs.next()){
                         bölüm_sayisi=myRs.getInt("bölüm_sayısı");
                         jTextField3.setText("Film/Dizi Adı : "+myRs.getString("program_adı")+" Bölüm Sayısı : "+myRs.getInt("bölüm_sayısı")+" Puan: "+myRs.getFloat("program_ortpuan"));
                            
                        }
                        
                                         
		}catch(Exception e){
			e.printStackTrace();
                            
                        
		}
        
        
        
        for(int i=1;i<=bölüm_sayisi;i++){
            jComboBox2.addItem(""+i);
        }
        Prolab2proje3netbeans izleyici=new Prolab2proje3netbeans();
        int k_id;
        k_id=izleyici.kullanıcıbulemail(email);
        if(kullanıcıfilm_kontrol(k_id,prg_id)==1){
        
        
        
        try {
                
                            Connection myConn=connectdb();
                            Statement myStat= (Statement) myConn.createStatement();
                            ResultSet myRs=  myStat.executeQuery("SELECT * FROM kullanıcıprogramtablosu WHERE kullanıcı_id='"+k_id+"' and program_id='"+prg_id+"'");
                            int kaldigi_bolum = 0;
                            String izledigi_sure = null;
                            while(myRs.next()){
                                
                                kaldigi_bolum=myRs.getInt("kaldığı_bölüm");
                                izledigi_sure=myRs.getString("izleme_süresi");
                                
                            }
                            jButton4.setText(kaldigi_bolum+". Bölüm "+izledigi_sure+"' da Kaldınız. Kaldığınız Yerden Devam Etmek İçin Tıklayınız");
                            jButton4.setVisible(true);
                            
                            
                            
                        }catch(Exception e){
                                e.printStackTrace();
                        }
        
        
        }
        
    }
    public filmarayüz() {
        
        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(248, 45));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setForeground(new java.awt.Color(255, 51, 51));
        jTextField1.setText("Puanla");
        jTextField1.setBorder(null);

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setForeground(new java.awt.Color(255, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "6", "7", "8", "9", "10" }));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Onayla");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jComboBox2.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox2.setForeground(new java.awt.Color(255, 51, 51));
        jComboBox2.setBorder(null);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setForeground(new java.awt.Color(255, 51, 51));
        jTextField2.setText("Bölümler");
        jTextField2.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 45));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 51, 51));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 0, 610, 45));

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Başlat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Durdur");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 668, 1024, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 1024, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        Prolab2proje3netbeans izleyici=new Prolab2proje3netbeans();
        int k_id;
        k_id=izleyici.kullanıcıbulemail(email);
        if(kullanıcıfilm_kontrol(k_id,prg_id)==0){
        JOptionPane.showMessageDialog(this,"Lütfen İzlemeden Oylama Yapmayanız");
        
        }else{
                        
            
                        String puan=jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
                        if(puan==" "){
                            JOptionPane.showMessageDialog(this,"Lütfen Bir Puan Seçiniz");
                        }else{
                        try {
                
                            Connection myConn=connectdb();
                            Statement myStat= (Statement) myConn.createStatement();
                            int myRs=  ((java.sql.Statement) myStat).executeUpdate("UPDATE kullanıcıprogramtablosu SET kullanıcı_puanı='"+puan+"'WHERE kullanıcı_id='"+k_id+"' and program_id='"+prg_id+"'");
                            
                            CallableStatement cs;
                            cs=myConn.prepareCall("{CALL update_rates6(?)}");
                            cs.setInt(1,prg_id);
                            ResultSet rs = cs.executeQuery();
                            
                            
                            
                        }catch(Exception e){
                                e.printStackTrace();
                        }
                        
                        
                            
                        }   
                        kullaniciarayüz.arayüzü_güncelle();
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
    

    
    
    public static String time(long izleme) throws ParseException {
    long millis = izleme;
    String hms = String.format("%02d:%02d:%02d", TimeUnit.MILLISECONDS.toHours(millis),
            TimeUnit.MILLISECONDS.toMinutes(millis) - TimeUnit.HOURS.toMinutes(TimeUnit.MILLISECONDS.toHours(millis)),
            TimeUnit.MILLISECONDS.toSeconds(millis) - TimeUnit.MINUTES.toSeconds(TimeUnit.MILLISECONDS.toMinutes(millis)));
//    System.out.println(hms);
    return hms;
}
    
    
    public static int kullanıcıfilm_kontrol(int k_id, int prg_id){
        try {
			Connection myConn=connectdb();
			Statement myStat= (Statement) myConn.createStatement();
			ResultSet myRs=  ((java.sql.Statement) myStat).executeQuery("SELECT * FROM kullanıcıprogramtablosu WHERE kullanıcı_id='"+k_id+"' and program_id='"+prg_id+"'");
                       
                        while(myRs.next()){
                            
                            
                            return 1;
                            
                        }
                        return 0;
                        
                     
		}catch(Exception e){
			e.printStackTrace();
                        
                        
                        
		}
        
        return -1;
        
        
    }
    
    public static Time film_zamancekme (int k_id, int prg_id){
        try {
			Connection myConn=connectdb();
			Statement myStat= (Statement) myConn.createStatement();
			ResultSet myRs=  ((java.sql.Statement) myStat).executeQuery("SELECT * FROM kullanıcıprogramtablosu WHERE kullanıcı_id='"+k_id+"' and program_id='"+prg_id+"'");
                       
                        while(myRs.next()){
                            
                           
                            return myRs.getTime("izleme_süresi");
                            
                        }
                        return null;
                        
                     
		}catch(Exception e){
			e.printStackTrace();
                        
                        
                        
		}
        
        return null;
        
        
    }
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int k_id;
        String sql_time = null;
        
        Prolab2proje3netbeans izleyici=new Prolab2proje3netbeans();
        k_id=izleyici.kullanıcıbulemail(email);
        
        
        izleme_süresi=currentTimeMillis()-baslangic_süresi;
       
        
        jButton1.setVisible(true);
        jButton2.setVisible(false);
        try {
             sql_time=time(izleme_süresi);
        
        } catch (ParseException ex) {
            Logger.getLogger(filmarayüz.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(kullanıcıfilm_kontrol(k_id,prg_id)==0){
        try {
			Connection myConn=connectdb();
			Statement myStat= (Statement) myConn.createStatement();
			int myRs=  ((java.sql.Statement) myStat).executeUpdate("INSERT INTO kullanıcıprogramtablosu values(CURRENT_TIMESTAMP(),'"+sql_time+"'"+",null,'"+(jComboBox2.getSelectedIndex()+1)+"','"+k_id+"','"+prg_id+"')");
                      
		}catch(Exception e){
			e.printStackTrace();
		}
        }else{
            
                long izleme_süresi2=currentTimeMillis()-baslangic_süresi;
                Time güncel_süre;
                
                güncel_süre=film_zamancekme(k_id,prg_id);
                long süre = güncel_süre.getTime();
                süre=süre+izleme_süresi2;
                String sql_time2=null;
                try {
                     sql_time2=time(süre);
                     
        
                } catch (ParseException ex) {
                     Logger.getLogger(filmarayüz.class.getName()).log(Level.SEVERE, null, ex);
                     
                     
                }

                

            
            try {
                
			Connection myConn=connectdb();
			Statement myStat= (Statement) myConn.createStatement();
                        
			int myRs=  ((java.sql.Statement) myStat).executeUpdate("UPDATE kullanıcıprogramtablosu SET izleme_tarihi=CURRENT_TIMESTAMP(),izleme_süresi='"+sql_time2+"',kaldığı_bölüm='"+(jComboBox2.getSelectedIndex()+1)+"' WHERE kullanıcı_id='"+k_id+"' and program_id='"+prg_id+"'");
                      
		}catch(Exception e){
			e.printStackTrace();
		}
            
            
            
        }
        
        baslangic_süresi=0;
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        baslangic_süresi=currentTimeMillis();
        jButton1.setVisible(false);
        jButton2.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                      
        int k_id;
        Prolab2proje3netbeans izleyici=new Prolab2proje3netbeans();
        k_id=izleyici.kullanıcıbulemail(email);
        
        try {
			Connection myConn=connectdb();
			Statement myStat= (Statement) myConn.createStatement();
			ResultSet myRs=  ((java.sql.Statement) myStat).executeQuery("SELECT * FROM kullanıcıprogramtablosu WHERE kullanıcı_id='"+k_id+"' and program_id='"+prg_id+"'");
                        int kaldigi_bolum = 0;
                        String izledigi_sure = null; 
                        while(myRs.next()){
                            
                        kaldigi_bolum=myRs.getInt("kaldığı_bölüm");
                        izledigi_sure=myRs.getString("izleme_süresi");
                            
                            
                        }
                        jComboBox2.setSelectedIndex(kaldigi_bolum-1);
                        
                     
		}catch(Exception e){
			e.printStackTrace();
                        
                        
                        
		}
        
        jButton4.setVisible(false);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed
    

    @Override
    public synchronized void addWindowListener(WindowListener l) {
        super.addWindowListener(l); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * @param args the command line arguments
     */
    protected void processWindowEvent(WindowEvent e) {
            super.processWindowEvent(e);
            
            if(baslangic_süresi!=0){
            if(e.getID() == WindowEvent.WINDOW_CLOSING) {
                int k_id;
        String sql_time = null;
        
        Prolab2proje3netbeans izleyici=new Prolab2proje3netbeans();
        k_id=izleyici.kullanıcıbulemail(email);
        
        
        izleme_süresi=currentTimeMillis()-baslangic_süresi;
       
        
        jButton1.setVisible(true);
        jButton2.setVisible(false);
        try {
             sql_time=time(izleme_süresi);
        
        } catch (ParseException ex) {
            Logger.getLogger(filmarayüz.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(kullanıcıfilm_kontrol(k_id,prg_id)==0){
        try {
			Connection myConn=connectdb();
			Statement myStat= (Statement) myConn.createStatement();
			int myRs=  ((java.sql.Statement) myStat).executeUpdate("INSERT INTO kullanıcıprogramtablosu values(CURRENT_TIMESTAMP(),'"+sql_time+"'"+",null,'"+(jComboBox2.getSelectedIndex()+1)+"','"+k_id+"','"+prg_id+"')");
                      
		}catch(Exception ex2){
			ex2.printStackTrace();
		}
        }else{
            
                long izleme_süresi2=currentTimeMillis()-baslangic_süresi;
                Time güncel_süre;
                
                güncel_süre=film_zamancekme(k_id,prg_id);
                long süre = güncel_süre.getTime();
                süre=süre+izleme_süresi2;
                String sql_time2=null;
                try {
                     sql_time2=time(süre);
                     
        
                } catch (ParseException ex) {
                     Logger.getLogger(filmarayüz.class.getName()).log(Level.SEVERE, null, ex);
                     
                     
                }

                

            
            try {
                
			Connection myConn=connectdb();
			Statement myStat= (Statement) myConn.createStatement();
                        
			int myRs=  ((java.sql.Statement) myStat).executeUpdate("UPDATE kullanıcıprogramtablosu SET izleme_tarihi=CURRENT_TIMESTAMP(),izleme_süresi='"+sql_time2+"',kaldığı_bölüm='"+(jComboBox2.getSelectedIndex()+1)+"' WHERE kullanıcı_id='"+k_id+"' and program_id='"+prg_id+"'");
                      
		}catch(Exception ex2){
			ex2.printStackTrace();
		}
            
            
            
        }
                
                
                
                
                
                
                
                
                
                
                
                System.exit(0);
            }
         }
        }
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(filmarayüz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(filmarayüz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(filmarayüz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(filmarayüz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new filmarayüz().setVisible(true);
            }
        });
    }
    

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    public static javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
